name: Publish draft

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.repository != 'Stichting-CROW/respec-repo-template' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - run: echo "noop"
      # - name: Checkout 🛎️
      #   uses: actions/checkout@v3

      # - name: Deploy live view 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4.3.3
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: ./docs # The folder the action should deploy.
      #     force: false
      #     clean-exclude: |
      #       v/**
      #     commit-message: |
      #       Deploying to docs.crow.nl from @ ${{ env.GITHUB_SHA}}

      #       Reason: After push by ${{ github.actor }}
